### ISSUE TITLE
Wifi adapter freezes

### ISSUE THREAD

**Issue by ilje** [Hygens/mt7610u_ubuntu_1610#2] opened 2017-08-01 16:49 UTC
Hi after some time my adapter freezes 

ac600
Bus 003 Device 002: ID 148f:761a Ralink Technology, Corp. 

```




[   58.024484] loading fw
[   58.025286] .
[   58.031247] .
[   58.037207] .
[   58.043161] .
[   58.048955] .
[   58.054786] .

[   58.362780] #
[   58.576124] RTMP_TimerListAdd: add timer obj ffffa98143e95090!
[   58.576125] RTMP_TimerListAdd: add timer obj ffffa98143e950e8!
[   58.576125] RTMP_TimerListAdd: add timer obj ffffa98143e95140!
[   58.576126] RTMP_TimerListAdd: add timer obj ffffa98143e95038!
[   58.576126] RTMP_TimerListAdd: add timer obj ffffa98143e94f30!
[   58.576127] RTMP_TimerListAdd: add timer obj ffffa98143e94f88!
[   58.576127] RTMP_TimerListAdd: add timer obj ffffa98143e27c88!
[   58.576128] RTMP_TimerListAdd: add timer obj ffffa98143e16b80!
[   58.576128] RTMP_TimerListAdd: add timer obj ffffa98143e16be0!
[   58.576128] RTMP_TimerListAdd: add timer obj ffffa98143e27db0!
[   58.576129] RTMP_TimerListAdd: add timer obj ffffa98143e27bd8!
[   58.576129] RTMP_TimerListAdd: add timer obj ffffa98143e27d58!
[   58.578219] no file read method, using vfs_read
[   58.578376] cfg_mode=13
[   58.578377] wmode_band_equal(): Band Not Equal!
[   58.578431] Key1Str is Invalid key length(0) or Type(0)
[   58.578436] Key2Str is Invalid key length(0) or Type(0)
[   58.578442] Key3Str is Invalid key length(0) or Type(0)
[   58.578447] Key4Str is Invalid key length(0) or Type(0)
[   58.578562] 1. Phy Mode = 61
[   58.578562] 2. Phy Mode = 61
[   58.578563] NVM is Efuse and its size =1d[1e0-1fc] 
[   58.582793] /iljex/paketi_src/mt7610u_ubuntu_1610/os/linux/../../chips/mt76x0.c:2114 assert (pAd->TxPower[choffset].Channel == 36)failed
[   58.586763] ERROR!!! 
[   58.586764] E2PROM: WRONG VERSION 0x2, should be 1
[   58.588361] mt76x0_read_tx_alc_info_from_eeprom: EEPROM_MT76x0_TEMPERATURE_OFFSET (0xD1) = 0xf8
[   58.588362] mt76x0_read_tx_alc_info_from_eeprom: TemperatureOffset = 0xfffffff8
[   58.588362] Temperature Tx ALC not enabled
[   58.594075] 3. Phy Mode = 61
[   58.594076] AntCfgInit: primary/secondary ant 0/1
[   58.599745] RTMPSetPhyMode: channel is out of range, use first channel=1 
[   58.600496] MCS Set = ff 00 00 00 01
[   58.610509] <==== rt28xx_init, Status=0
[   58.610947] 0x1300 = 00064300
[   58.610948] RTMPDrvSTAOpen(1):Check if PDMA is idle!
[   58.611028] RTMPDrvSTAOpen(2):Check if PDMA is idle!
[   58.635874] /iljex/paketi_src/mt7610u_ubuntu_1610/os/linux/../../common/cmm_asic.c:2112 assert KeyIdx < 4failed
[   58.636038] /iljex/paketi_src/mt7610u_ubuntu_1610/os/linux/../../common/cmm_asic.c:2112 assert KeyIdx < 4failed
[   63.425147] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[   63.425236] ==>rt_ioctl_siwfreq::SIOCSIWFREQ(Channel=1)
[   63.533591] PeerBeaconAtJoinAction(): HT-CtrlChannel=1, CentralChannel=>3
[   63.533591] PeerBeaconAtJoinAction(): Set CentralChannel=3
[   63.533593] AdjustChannelRelatedValue(): Input BW=1, rf_channel=3, vht_bw=1, Channel=1, vht_cent_ch=1!
[   64.529617] Rcv Wcid(1) AddBAReq
[   64.529620] Start Seq = 00000002
[   64.529624] RTMP_TimerListAdd: add timer obj ffffa98143ee4d98!
[   64.533103] RTMP_TimerListAdd: add timer obj ffffa98143ee1578!
[   64.539549] Rcv Wcid(1) AddBAReq
[   64.539551] Start Seq = 00000001
[   64.539554] RTMP_TimerListAdd: add timer obj ffffa98143ee4e30!
[   69.931383] RTMP_TimerListAdd: add timer obj ffffa98143ee15e8!
[   69.939666] Rcv Wcid(1) AddBAReq
[   69.939667] Start Seq = 00000001
[   69.939668] RTMP_TimerListAdd: add timer obj ffffa98143ee4ec8!
[  234.503592] DeQueueRunning[0]= TRUE!
[  234.534920] DeQueueRunning[0]= TRUE!
[  257.570668] DeQueueRunning[0]= TRUE!
[  257.762615] DeQueueRunning[0]= TRUE!
[  264.931108] DeQueueRunning[0]= TRUE!
[  267.176391] DeQueueRunning[0]= TRUE!
[  290.369210] DeQueueRunning[0]= TRUE!
[  291.753123] DeQueueRunning[0]= TRUE!
[  357.029114] DeQueueRunning[0]= TRUE!
[  378.607530] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[  378.607532] ACT-BuildIntolerantChannelRep(Size=0)
[  378.607997] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[  379.366168] cfd, flush one!
[  380.750153] Rcv Wcid(1) AddBAReq
[  380.750158] Start Seq = 00000d50
[  516.602833] DeQueueRunning[0]= TRUE!
[  692.968014] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[  692.968015] ACT-BuildIntolerantChannelRep(Size=0)
[  692.968117] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[ 1007.303491] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[ 1007.303493] ACT-BuildIntolerantChannelRep(Size=0)
[ 1007.304600] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[ 1321.936986] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[ 1321.936988] ACT-BuildIntolerantChannelRep(Size=0)
[ 1321.937196] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[ 1322.155932] aef, flush one!
[ 1322.386917] af0, flush one!
[ 1322.559068] af6, flush one!
[ 1332.801921] Rcv Wcid(1) AddBAReq
[ 1332.801923] Start Seq = 00000b34
[ 1636.585462] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[ 1636.585464] ACT-BuildIntolerantChannelRep(Size=0)
[ 1636.585617] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[ 1928.328874] DeQueueRunning[0]= TRUE!
[ 1950.865915] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[ 1950.865916] ACT-BuildIntolerantChannelRep(Size=0)
[ 1950.866061] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[ 1951.536436] 2fd, flush one!
[ 1952.006480] 2fe, flush one!
[ 1952.227946] Rcv Wcid(1) AddBAReq
[ 1952.227947] Start Seq = 00000348
[ 2265.643399] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[ 2265.643400] ACT-BuildIntolerantChannelRep(Size=0)
[ 2265.643526] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[ 2579.890897] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[ 2579.890898] ACT-BuildIntolerantChannelRep(Size=0)
[ 2579.891025] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[ 2580.202477] 921, flush one!
[ 2587.404264] Rcv Wcid(1) AddBAReq
[ 2587.404265] Start Seq = 00000964
[ 3030.712904] DeQueueRunning[0]= TRUE!
[ 3079.818208] DeQueueRunning[0]= TRUE!
[ 3091.774120] DeQueueRunning[0]= TRUE!
[ 3209.050876] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[ 3209.050878] ACT-BuildIntolerantChannelRep(Size=0)
[ 3209.050988] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[ 3212.230660] Rcv Wcid(1) AddBAReq
[ 3212.230661] Start Seq = 00000967
[ 3523.404335] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[ 3523.404336] ACT-BuildIntolerantChannelRep(Size=0)
[ 3523.404824] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[ 3759.763261] nf_conntrack: default automatic helper assignment has been turned off for security reasons and CT-based  firewall rule not found. Use the iptables CT target to attach helpers instead.
[ 3837.859846] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[ 3837.859849] ACT-BuildIntolerantChannelRep(Size=0)
[ 3837.860352] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[ 3843.047695] Rcv Wcid(1) AddBAReq
[ 3843.047697] Start Seq = 00000d7f
[ 4121.743780] Rcv Wcid(1) AddBAReq
[ 4121.743782] Start Seq = 00000003
[ 4466.813751] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[ 4466.813752] ACT-BuildIntolerantChannelRep(Size=0)
[ 4466.813878] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[ 4781.213233] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[ 4781.213237] ACT-BuildIntolerantChannelRep(Size=0)
[ 4781.213427] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[ 4784.012087] Rcv Wcid(1) AddBAReq
[ 4784.012090] Start Seq = 00000d74
[ 5095.605736] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[ 5095.605739] ACT-BuildIntolerantChannelRep(Size=0)
[ 5095.606629] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[ 5102.218267] d02, flush one!
[ 5117.240401] Rcv Wcid(1) AddBAReq
[ 5117.240403] Start Seq = 00000d4b
[ 5410.231223] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[ 5410.231227] ACT-BuildIntolerantChannelRep(Size=0)
[ 5410.231434] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[ 5413.389771] Rcv Wcid(1) AddBAReq
[ 5413.389772] Start Seq = 00000424
[ 5724.535690] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[ 5724.535692] ACT-BuildIntolerantChannelRep(Size=0)
[ 5724.536161] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[ 6039.144183] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[ 6039.144185] ACT-BuildIntolerantChannelRep(Size=0)
[ 6039.144304] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[ 6053.033778] 50, flush one!
[ 6078.175118] Rcv Wcid(1) AddBAReq
[ 6078.175119] Start Seq = 00000099
[ 6299.945913] DeQueueRunning[0]= TRUE!
[ 6381.358190] DeQueueRunning[0]= TRUE!
[ 6667.153094] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[ 6667.153096] ACT-BuildIntolerantChannelRep(Size=0)
[ 6667.153227] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[ 6682.401509] Rcv Wcid(1) AddBAReq
[ 6682.401511] Start Seq = 00000941
[ 6720.049390] DeQueueRunning[0]= TRUE!
[ 6727.109429] DeQueueRunning[0]= TRUE!
[ 6781.993725] DeQueueRunning[0]= TRUE!
[ 6981.712583] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[ 6981.712585] ACT-BuildIntolerantChannelRep(Size=0)
[ 6981.712750] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[ 6983.598066] Rcv Wcid(1) AddBAReq
[ 6983.598067] Start Seq = 0000025c
[ 7135.393823] DeQueueRunning[0]= TRUE!
[ 7295.722031] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[ 7295.722034] ACT-BuildIntolerantChannelRep(Size=0)
[ 7295.722526] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[ 7561.203697] Rcv Wcid(1) AddBAReq
[ 7561.203698] Start Seq = 0000001e
[ 7610.050501] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[ 7610.050503] ACT-BuildIntolerantChannelRep(Size=0)
[ 7610.050680] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[ 7618.301545] Rcv Wcid(1) AddBAReq
[ 7618.301546] Start Seq = 00000ecd
[ 7724.633355] DeQueueRunning[0]= TRUE!
[ 7804.210734] DeQueueRunning[0]= TRUE!
[ 7924.145963] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[ 7924.145965] ACT-BuildIntolerantChannelRep(Size=0)
[ 7924.146079] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[ 8238.866458] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[ 8238.866460] ACT-BuildIntolerantChannelRep(Size=0)
[ 8238.866976] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[ 8252.341812] Rcv Wcid(1) AddBAReq
[ 8252.341813] Start Seq = 00000210
[ 8553.236934] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[ 8553.236937] ACT-BuildIntolerantChannelRep(Size=0)
[ 8553.237084] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[ 8760.234849] DeQueueRunning[0]= TRUE!
[ 8760.234874] DeQueueRunning[0]= TRUE!
[ 8863.876353] DeQueueRunning[0]= TRUE!
[ 8926.038177] DeQueueRunning[0]= TRUE!
[ 9182.316881] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[ 9182.316882] ACT-BuildIntolerantChannelRep(Size=0)
[ 9182.317025] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[ 9183.471132] 7a8, flush one!
[ 9183.809418] 7b8, flush one!
[ 9202.148432] Rcv Wcid(1) AddBAReq
[ 9202.148433] Start Seq = 000007f1
[ 9811.405864] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[ 9811.405867] ACT-BuildIntolerantChannelRep(Size=0)
[ 9811.406652] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[ 9823.103076] Rcv Wcid(1) AddBAReq
[ 9823.103078] Start Seq = 00000143
[10125.886349] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[10125.886352] ACT-BuildIntolerantChannelRep(Size=0)
[10125.886530] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[10135.022726] Rcv Wcid(1) AddBAReq
[10135.022728] Start Seq = 00000e7d
[10440.622837] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[10440.622838] ACT-BuildIntolerantChannelRep(Size=0)
[10440.622968] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[10755.376359] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[10755.376363] ACT-BuildIntolerantChannelRep(Size=0)
[10755.376486] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[10756.362023] 19, flush one!
[10782.921191] Rcv Wcid(1) AddBAReq
[10782.921192] Start Seq = 00000063
[11069.871835] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[11069.871840] ACT-BuildIntolerantChannelRep(Size=0)
[11069.871985] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[11072.050470] fe, flush one!
[11079.707810] Rcv Wcid(1) AddBAReq
[11079.707811] Start Seq = 00000143
[11568.452819] DeQueueRunning[0]= TRUE!
[11699.337813] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[11699.337816] ACT-BuildIntolerantChannelRep(Size=0)
[11699.337906] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[11830.043687] DeQueueRunning[0]= TRUE!
[12014.009270] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[12014.009273] ACT-BuildIntolerantChannelRep(Size=0)
[12014.009366] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[12021.514521] dd, flush one!
[12041.163715] Rcv Wcid(1) AddBAReq
[12041.163720] Start Seq = 00000126
[12072.404793] DeQueueRunning[0]= TRUE!
[12328.625750] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[12328.625751] ACT-BuildIntolerantChannelRep(Size=0)
[12328.625875] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[12643.106249] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[12643.106251] ACT-BuildIntolerantChannelRep(Size=0)
[12643.106391] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[12657.699304] Rcv Wcid(1) AddBAReq
[12657.699305] Start Seq = 000008b0
[12957.810749] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[12957.810750] ACT-BuildIntolerantChannelRep(Size=0)
[12957.810832] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[13272.563259] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[13272.563263] ACT-BuildIntolerantChannelRep(Size=0)
[13272.563382] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[13274.760065] a43, flush one!
[13275.241507] a44, flush one!
[13275.716689] a45, flush one!
[13278.504221] Rcv Wcid(1) AddBAReq
[13278.504224] Start Seq = 00000a90
[13586.987721] ACT - Update2040CoexistFrameAndNotify. BSSCoexist2040 = 1. EventANo = 0. 
[13586.987723] ACT-BuildIntolerantChannelRep(Size=0)
[13586.988197] ===>rt_ioctl_giwscan. 1(1) BSS returned, data->length = 293
[13750.372755] DeQueueRunning[0]= TRUE!
[13753.961564] DeQueueRunning[0]= TRUE!
[13755.734424] DeQueueRunning[0]= TRUE!
[13766.719583] DeQueueRunning[0]= TRUE!
[13768.217179] DeQueueRunning[0]= TRUE!
[13769.388847] DeQueueRunning[0]= TRUE!
[13770.002144] DeQueueRunning[0]= TRUE!
[13771.742215] DeQueueRunning[0]= TRUE!
[13773.139272] DeQueueRunning[0]= TRUE!
[13787.216099] DeQueueRunning[0]= TRUE!
[13787.870630] DeQueueRunning[0]= TRUE!
[13787.915663] DeQueueRunning[0]= TRUE!
[13789.815032] DeQueueRunning[0]= TRUE!
[13800.137036] DeQueueRunning[0]= TRUE!
[13806.123031] DeQueueRunning[0]= TRUE!
[13808.894339] DeQueueRunning[0]= TRUE!
[13813.122783] DeQueueRunning[0]= TRUE!
[13814.004927] DeQueueRunning[0]= TRUE!
[13815.372243] DeQueueRunning[0]= TRUE!
[13816.175860] DeQueueRunning[0]= TRUE!
[13823.405707] DeQueueRunning[0]= TRUE!
[13826.902302] DeQueueRunning[0]= TRUE!
[13827.059955] DeQueueRunning[0]= TRUE!
[13828.392389] DeQueueRunning[0]= TRUE!
[13828.464150] DeQueueRunning[0]= TRUE!
[13830.214182] DeQueueRunning[0]= TRUE!
[13830.322414] DeQueueRunning[0]= TRUE!
[13831.495898] DeQueueRunning[0]= TRUE!
[13840.810988] DeQueueRunning[0]= TRUE!
[13845.699357] DeQueueRunning[0]= TRUE!
[13848.439069] DeQueueRunning[0]= TRUE!
[13856.671377] DeQueueRunning[0]= TRUE!
[13856.925594] DeQueueRunning[0]= TRUE!
[13856.971341] DeQueueRunning[0]= TRUE!
[13858.182007] DeQueueRunning[0]= TRUE!
[13859.144767] DeQueueRunning[0]= TRUE!
[13859.669885] DeQueueRunning[0]= TRUE!
[13861.359262] DeQueueRunning[0]= TRUE!
[13866.579948] DeQueueRunning[0]= TRUE!
[13869.518305] DeQueueRunning[0]= TRUE!
[13869.750460] DeQueueRunning[0]= TRUE!
[13870.522958] DeQueueRunning[0]= TRUE!
[13871.071403] DeQueueRunning[0]= TRUE!
[13871.801110] DeQueueRunning[0]= TRUE!
[13872.329730] DeQueueRunning[0]= TRUE!
[13877.998665] DeQueueRunning[0]= TRUE!
[13877.998921] DeQueueRunning[0]= TRUE!
[13879.870146] DeQueueRunning[0]= TRUE!
[13886.888217] DeQueueRunning[0]= TRUE!
[13887.875151] DeQueueRunning[0]= TRUE!
[13891.994286] DeQueueRunning[0]= TRUE!
[13893.406151] DeQueueRunning[0]= TRUE!
[13894.642797] DeQueueRunning[0]= TRUE!
[13894.825915] DeQueueRunning[0]= TRUE!
[13894.988138] DeQueueRunning[0]= TRUE!
[13901.400664] DeQueueRunning[0]= TRUE!
[13901.573877] DeQueueRunning[0]= TRUE!
[13907.683462] DeQueueRunning[0]= TRUE!
[13913.127045] DeQueueRunning[0]= TRUE!
[13919.523055] DeQueueRunning[0]= TRUE!
[13919.982278] DeQueueRunning[0]= TRUE!
[13930.908742] DeQueueRunning[0]= TRUE!
[13931.811997] DeQueueRunning[0]= TRUE!
[13934.859488] DeQueueRunning[0]= TRUE!
[13935.226472] DeQueueRunning[0]= TRUE!
[13943.886957] DeQueueRunning[0]= TRUE!
[13943.967591] DeQueueRunning[0]= TRUE!
[13951.153166] DeQueueRunning[0]= TRUE!
[13951.485327] DeQueueRunning[0]= TRUE!
[13962.084701] DeQueueRunning[0]= TRUE!
[13965.141692] DeQueueRunning[0]= TRUE!
[13966.022687] DeQueueRunning[0]= TRUE!
[13969.150939] DeQueueRunning[0]= TRUE!
[13971.211735] DeQueueRunning[0]= TRUE!
[13971.640255] DeQueueRunning[0]= TRUE!
[13975.845038] DeQueueRunning[0]= TRUE!
[13980.273429] DeQueueRunning[0]= TRUE!
[13983.235267] DeQueueRunning[0]= TRUE!
[13987.037040] DeQueueRunning[0]= TRUE!
[13987.273370] DeQueueRunning[0]= TRUE!
[13988.373337] DeQueueRunning[0]= TRUE!
[13988.884726] DeQueueRunning[0]= TRUE!
```

**Comment by Hygens** [comment] 2017-08-01 17:39
Hi,

If you using other kernel different that posted on Wiki the problem is adapt that driver for new kernel and possibly exists some other driver already installed in conflict with that installation.
Unhappy in that moment I do not have time for help more than that.
The immediate analysis are:

1) Analyse your kernel version because need 4.8.0-41 atmost:
execute "uname -a" and observe what kernel you are using if the kernel is major then version on here need uninstall and maintain the old kernel for while. You can block updates for manually on update manager(search on google for that).
2) Analyse if exists some device on your kernel for the same driver if exists you need uninstall that and uninstall other and re-install that.
3) The more important details is if you searching for linksys dongle driver not is that. That is for TPLINK T2UH AC600 and only that. If you have installed other driver you need uninstall each package that you have installed because your system can unstable with two distinct drivers.
4) If you not have good knowledge about what you do for that and if possible install one clean copy or your Ubuntu or Linux Mint and install the driver. Here I'm using Linux Mint 18.2 and functioning like a charm. 
5) If you using pure debian distro or debian based distro this driver is not for that too.

For while that two tricks can save you and continue using your device.

**Comment by ilje** [comment] 2017-08-01 22:16
Hi thx for answer and sorry for my bad en
I use Fedora 26
kernel : Linux localhost.localdomain 4.11.11-300.fc26.x86_64 #1 SMP Mon Jul 17 16:32:11 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
This is my adapter
`http://www.tp-link.com/us/products/details/cat-5520_Archer-T2U.html`
I found some other mt drivers in my kernel
mt7662.bin mt7622_rom_patch.bin 
mt7601u.ko.xz
do i need remove that ?
<a href="https://ibb.co/bHhDS5"><img src="https://preview.ibb.co/cBiyuk/ac600.png" alt="ac600" border="0" /></a>

**Comment by Hygens** [comment] 2017-08-01 22:51
Sorry, this driver is not for Fedora is for Ubuntu Mint and is for T2UH not T2U. That issue is not exists for exactly that driver.
You need search for that driver for Fedora and for your kernel.
The first questions is that driver is not for 4.11.11 kernel it's for 4.8.0-41 kernel.
Sorry I do not help you more then that.
I'm closing the issue.

**Closed as completed by Hygens** 2017-08-01 22:51 UTC
